//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<bool> Descuento { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idStock { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
